<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Sanity"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="22.645">
  <properties />
            <testcase name="anAustralianComingToUKForTourism" time="1.166" classname="gov.uk.check.visa.testsuite.VisaConfirmationTest">
                <failure type="java.lang.AssertionError"
                  message="Result not found expected [You will not ned a visa to come to the UK] but found [You will not need a visa to come to the UK]"
              >
<![CDATA[java.lang.AssertionError: Result not found expected [You will not ned a visa to come to the UK] but found [You will not need a visa to come to the UK]
  org.testng.Assert.fail(Assert.java:110)
  org.testng.Assert.failNotEquals(Assert.java:1413)
  org.testng.Assert.assertEqualsImpl(Assert.java:149)
  org.testng.Assert.assertEquals(Assert.java:131)
  org.testng.Assert.assertEquals(Assert.java:655)
  gov.uk.check.visa.testsuite.VisaConfirmationTest.anAustralianComingToUKForTourism(VisaConfirmationTest.java:41)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.util.ArrayList.forEach(ArrayList.java:1249)
  org.testng.TestRunner.privateRun(TestRunner.java:808)
  org.testng.TestRunner.run(TestRunner.java:603)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
  org.testng.SuiteRunner.run(SuiteRunner.java:326)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
  org.testng.TestNG.runSuites(TestNG.java:1092)
  org.testng.TestNG.run(TestNG.java:1060)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="aColumbianNationalComingToTheUKToJoinAPartnerForALongStayTheyDoHaveAnArticle10Or20Card" time="21.479" classname="gov.uk.check.visa.testsuite.VisaConfirmationTest" />
      
</testsuite>
